// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbyM4VMBVpwtXveo5VRGR3XjLF1dmZ93c',
    appId: '1:414321291386:android:f16d608ce656fa77e30bc3',
    messagingSenderId: '414321291386',
    projectId: 'astroreal-e7628',
    storageBucket: 'astroreal-e7628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGig8YaKhMxct7fBnn4NT-AJv1dt4HK3Y',
    appId: '1:414321291386:ios:8e127fb85768b612e30bc3',
    messagingSenderId: '414321291386',
    projectId: 'astroreal-e7628',
    storageBucket: 'astroreal-e7628.firebasestorage.app',
    iosBundleId: 'com.example.astroreal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLGIweWh82NahD34vqF5D2ejofBD5u6FA',
    appId: '1:414321291386:web:9da88c58e7a081dfe30bc3',
    messagingSenderId: '414321291386',
    projectId: 'astroreal-e7628',
    authDomain: 'astroreal-e7628.firebaseapp.com',
    storageBucket: 'astroreal-e7628.firebasestorage.app',
    measurementId: 'G-5DQQD6Z9Q3',
  );
}
